### PR TITLE
Unit test to demonstrate #15

### PR DESCRIPTION
**Pull request by madhephaestus**
I wrote a stripped down unit test to demonstrate the issue i have been describing in #15 . This unit test will test to see that when the extrude function is called on convex polygons, that the triangulation function does not fall off the edge and begin placing triangles inside out.

### CODE REVIEW

**Comment by madhephaestus** [comment]
This will fail the travis build because it includes a unit test that demonstrated a fault and at this time is not passing.

**Comment by miho** [comment]
Thanks for preparing the test. I'll have a look at it.

**Comment by miho** [comment]
> that the triangulation function does not fall off the edge and begin placing triangles inside out.

Your assumption in the test is wrong. The increased number of triangles does not come from bad orientation etc.

Just try this with regular primitives such as two spheres and it will fail as well if you don't enable optimization.

**Comment by madhephaestus** [comment]
How would i enable optimizations?

**Comment by miho** [comment]
See your unit test. I modified it to work properly. But I doubt that this
is the root of your problem.

--
Dipl.-Math. Michael Hoffer

Twitter: @mihosoft
Webpage: www.mihosoft.eu

Goethe-Zentrum für Wissenschaftliches Rechnen (G-CSC)
Goethe-Universität
Kettenhofweg 139
60325 Frankfurt am Main
phone: +49 69 798 25254
info@michaelhoffer.de

2016-11-12 20:42 GMT+01:00 Kevin Harrington <notifications@github.com>:

**Comment by madhephaestus** [comment]
Why is this mode not the default?

**Comment by miho** [comment]
Because it does not work 100% reliable. There are edge cases that I didn't test so far.

**Pull request merged**
