### PR TITLE
AWT dependencies removed from clean-room text extrude

### PR DESCRIPTION
**Pull request by madhephaestus**
I added a unit test to verify that the text extrude functions execute without error. I also verified the STL produced represents the text entered, in the correct orientation.

### CODE REVIEW

**Comment by madhephaestus** [comment]
Any comments on this to make it more compatible?

**Comment by miho** [comment]
Thanks. Will have a look at it soon...

**Comment by miho** [comment]
Unfortunately, the text sample does not work with your PR. Here's an example:

image

**Comment by miho** [comment]
There are also many errors, such as

```
50 [main] INFO eu.mihosoft.vrl.v3d.ext.org.poly2tri.DTSweepConstraint - Failed to create constraint [27.6328125,-0.87890625]=[27.6328125,-0.87890625]
50 [main] INFO eu.mihosoft.vrl.v3d.ext.org.poly2tri.DTSweepConstraint - Failed to create constraint [27.6328125,-0.87890625]=[27.6328125,-0.87890625]
50 [main] INFO eu.mihosoft.vrl.v3d.ext.org.poly2tri.DTSweepConstraint - Failed to create constraint [27.6328125,-0.87890625]=[27.6328125,-0.87890625]
50 [main] INFO eu.mihosoft.vrl.v3d.ext.org.poly2tri.DTSweepConstraint - Failed to create constraint [27.6328125,-0.87890625]=[27.6328125,-0.87890625]
50 [main] INFO eu.mihosoft.vrl.v3d.ext.org.poly2tri.DTSweepConstraint - Failed to create constraint [27.6328125,-0.87890625]=[27.6328125,-0.87890625]
50 [main] INFO eu.mihosoft.vrl.v3d.ext.org.poly2tri.DTSweepConstraint - Failed to create constraint [27.6328125,-0.87890625]=[27.6328125,-0.87890625]
50 [main] INFO eu.mihosoft.vrl.v3d.ext.org.poly2tri.DTSweepConstraint - Failed to create constraint [27.6328125,-0.87890625]=[27.6328125,-0.87890625]
50 [main] INFO eu.mihosoft.vrl.v3d.ext.org.poly2tri.DTSweepConstraint - Failed to create constraint [27.6328125,-0.87890625]=[27.6328125,-0.87890625]
50 [main] INFO eu.mihosoft.vrl.v3d.ext.org.poly2tri.DTSweepConstraint - Failed to create constraint [27.6328125,-0.87890625]=[27.6328125,-0.87890625]
50 [main] INFO eu.mihosoft.vrl.v3d.ext.org.poly2tri.DTSweepConstraint - Failed to create constraint [27.6328125,-0.87890625]=[27.6328125,-0.87890625]
```

**Pull request closed without merging**
